using System.Collections.Generic;

namespace Nexo.Feature.Networking.Models;

/// <summary>
/// Configuration models for networking setup
/// </summary>
public partial class NetworkingRequest
{
    // This partial class contains configuration models
}

/// <summary>
/// Security settings for networking
/// </summary>
public record SecuritySettings
{
    /// <summary>
    /// Enable encryption
    /// </summary>
    public bool EnableEncryption { get; init; } = true;
    
    /// <summary>
    /// Enable authentication
    /// </summary>
    public bool EnableAuthentication { get; init; } = true;
    
    /// <summary>
    /// Enable anti-cheat
    /// </summary>
    public bool EnableAntiCheat { get; init; } = false;
    
    /// <summary>
    /// Enable rate limiting
    /// </summary>
    public bool EnableRateLimiting { get; init; } = true;
    
    /// <summary>
    /// Maximum connections per IP
    /// </summary>
    public int MaxConnectionsPerIP { get; init; } = 5;
    
    /// <summary>
    /// Connection timeout in seconds
    /// </summary>
    public int ConnectionTimeoutSeconds { get; init; } = 30;
}

/// <summary>
/// Networking configuration
/// </summary>
public record NetworkingConfiguration
{
    /// <summary>
    /// Configuration name
    /// </summary>
    public string Name { get; init; } = string.Empty;
    
    /// <summary>
    /// Networking type
    /// </summary>
    public NetworkingType Type { get; init; }
    
    /// <summary>
    /// Server configuration
    /// </summary>
    public ServerConfiguration Server { get; init; } = new();
    
    /// <summary>
    /// Client configuration
    /// </summary>
    public ClientConfiguration Client { get; init; } = new();
    
    /// <summary>
    /// Security settings
    /// </summary>
    public SecuritySettings Security { get; init; } = new();
    
    /// <summary>
    /// Network events
    /// </summary>
    public List<NetworkEvent> Events { get; init; } = new();
    
    /// <summary>
    /// Message types
    /// </summary>
    public List<MessageType> MessageTypes { get; init; } = new();
}

/// <summary>
/// Server configuration
/// </summary>
public record ServerConfiguration
{
    /// <summary>
    /// Server IP address
    /// </summary>
    public string IPAddress { get; init; } = "0.0.0.0";
    
    /// <summary>
    /// Server port
    /// </summary>
    public int Port { get; init; } = 7777;
    
    /// <summary>
    /// Maximum players
    /// </summary>
    public int MaxPlayers { get; init; } = 4;
    
    /// <summary>
    /// Server name
    /// </summary>
    public string Name { get; init; } = "Nexo Game Server";
    
    /// <summary>
    /// Server description
    /// </summary>
    public string Description { get; init; } = "Generated by Nexo";
    
    /// <summary>
    /// Tick rate (updates per second)
    /// </summary>
    public int TickRate { get; init; } = 60;
    
    /// <summary>
    /// Enable server discovery
    /// </summary>
    public bool EnableDiscovery { get; init; } = true;
}

/// <summary>
/// Client configuration
/// </summary>
public record ClientConfiguration
{
    /// <summary>
    /// Default server IP
    /// </summary>
    public string DefaultServerIP { get; init; } = "127.0.0.1";
    
    /// <summary>
    /// Default server port
    /// </summary>
    public int DefaultServerPort { get; init; } = 7777;
    
    /// <summary>
    /// Connection timeout
    /// </summary>
    public int ConnectionTimeoutMs { get; init; } = 5000;
    
    /// <summary>
    /// Reconnection attempts
    /// </summary>
    public int ReconnectionAttempts { get; init; } = 3;
    
    /// <summary>
    /// Enable auto-reconnect
    /// </summary>
    public bool EnableAutoReconnect { get; init; } = true;
}
