using FluentAssertions;
using Ashlar.Infrastructure.Certification;
using Ashlar.Tests.Infrastructure.Certification.Fixtures;
using Xunit;

namespace Ashlar.Tests.Infrastructure.Tests.Certification;

/// <summary>
/// The certification BYPASS that the multi-file refusal shipped with, and the loader-side compile
/// failure it could not tell apart from a broken candidate.
///
/// <para>The refusal itself was right: a certificate binds ONE content hash over ONE source text,
/// so a brick spanning several files must be refused rather than certified against whichever file
/// the filesystem returned first. What was wrong was the definition of "file". The loader excluded
/// <c>*.g.cs</c>, <c>*.Designer.cs</c> and <c>*.AssemblyAttributes.cs</c> by NAME, on the
/// assumption that those names mean "generated by the build". The SDK excludes <c>obj/</c> and
/// <c>bin/</c> and compiles all three of those names everywhere else — so a file called
/// <c>Helper.g.cs</c> was compiled into the assembly while being invisible to the content hash,
/// the analyzer fence and the mutation leg, AND slipped the multi-file refusal. Two bricks with
/// different behaviour certified Trusted under the same contentHash.</para>
///
/// <para>These facts pin the rule that replaced the name list: the source set is what the COMPILER
/// compiles, a project whose compile items the gate cannot model is a refusal rather than a guess,
/// and the reference set the loader hands the fence contains only assemblies the compiler can
/// actually open.</para>
/// </summary>
[Trait("Category", "Certification")]
public sealed class BrickCompiledSourceSetTests : IDisposable
{
    private readonly string _dir;

    public BrickCompiledSourceSetTests()
    {
        _dir = Path.Combine(Path.GetTempPath(), "ashlar-compiled-set-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_dir);
        WriteProject("<Project Sdk=\"Microsoft.NET.Sdk\" />");
    }

    public void Dispose()
    {
        if (Directory.Exists(_dir))
            Directory.Delete(_dir, recursive: true);
    }

    private string Csproj => Path.Combine(_dir, "Brick.csproj");

    private void WriteProject(string xml) => File.WriteAllText(Csproj, xml);

    private void Write(string relativePath, string content)
    {
        var full = Path.Combine(_dir, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    [Theory]
    [InlineData("Helper.g.cs")]
    [InlineData("Helper.Designer.cs")]
    [InlineData("Helper.generated.cs")]
    [InlineData("Helper.AssemblyAttributes.cs")]
    [InlineData("Helper.AssemblyInfo.cs")]
    public void A_file_the_compiler_compiles_is_part_of_the_brick_whatever_it_is_called(string name)
    {
        // Every one of these names was on the loader's exclusion list, and the SDK compiles every
        // one of them. A name is not evidence about what the compiler does.
        Write("Brick.cs", "public sealed class DemoBrick { }");
        Write(name, "public static class Helper { public static int Answer() => 42; }");

        BrickCertificationProjectLoader.FindBrickSourceFiles(_dir)
            .Select(Path.GetFileName)
            .Should().BeEquivalentTo(["Brick.cs", name],
                "the source set is what the compiler compiles; a file inside the assembly but outside the "
                + "content hash is code that no leg of the gate ever judged");
    }

    [Fact]
    public async Task A_second_file_named_like_generated_output_no_longer_slips_the_multi_file_refusal()
    {
        // The bypass, end to end: name the second file Helper.g.cs and the brick certified as if it
        // were a single file, with the extra behaviour outside the hash.
        Write("Brick.cs", "public sealed class DemoBrick { }");
        Write("Helper.g.cs", "public static class Helper { }");

        var act = async () => await BrickCertificationProjectLoader.LoadAsync(
            _dir, Path.Combine(_dir, "witness.json"));

        (await act.Should().ThrowAsync<InvalidOperationException>())
            .WithMessage("*Multi-file brick refused*")
            .And.Message.Should().Contain("Helper.g.cs");
    }

    [Fact]
    public void Real_build_output_is_still_excluded_by_directory()
    {
        // Dropping the name list must not start hashing the build's own output. The directory rule
        // is the compiler's own rule, and it is enough.
        Write("Brick.cs", "public sealed class DemoBrick { }");
        Write("obj/Debug/Brick.AssemblyInfo.cs", "// generated");
        Write("obj/Debug/Brick.GlobalUsings.g.cs", "// generated");
        Write("bin/Debug/Leftover.cs", "// stale output");

        BrickCertificationProjectLoader.FindBrickSourceFiles(_dir)
            .Select(Path.GetFileName)
            .Should().BeEquivalentTo(["Brick.cs"]);
    }

    [Theory]
    [InlineData("EnableDefaultItems")]
    [InlineData("EnableDefaultCompileItems")]
    public async Task Switching_off_the_default_compile_items_is_refused_not_guessed_at(string property)
    {
        // With the default glob off, the compiled set is whatever the project's explicit Compile
        // items name, and walking the directory no longer models it. A source set the gate cannot
        // know is a refusal — an omission here is a signed record asserting more than was checked.
        Write("Brick.cs", "public sealed class DemoBrick { }");
        WriteProject($"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup><{property}>false</{property}></PropertyGroup>
              <ItemGroup><Compile Include="Brick.cs" /></ItemGroup>
            </Project>
            """);

        var act = async () => await BrickCertificationProjectLoader.LoadAsync(
            _dir, Path.Combine(_dir, "witness.json"));

        (await act.Should().ThrowAsync<InvalidOperationException>())
            .And.Message.Should().Contain(property).And.Contain("Fix:");
    }

    [Theory]
    [InlineData(@"..\Shared\Helper.cs")]
    [InlineData("../Shared/Helper.cs")]
    [InlineData("$(SharedDir)/Helper.cs")]
    public void A_compile_item_from_outside_the_brick_directory_is_refused(string pattern)
    {
        Write("Brick.cs", "public sealed class DemoBrick { }");
        WriteProject($"""
            <Project Sdk="Microsoft.NET.Sdk">
              <ItemGroup><Compile Include="{pattern}" /></ItemGroup>
            </Project>
            """);

        var act = () => BrickCertificationProjectLoader.AssertCompileSetIsHashable(Csproj, _dir);

        act.Should().Throw<InvalidOperationException>()
            .WithMessage("*Brick project refused*")
            .And.Message.Should().Contain("Fix:");
    }

    [Fact]
    public void An_ordinary_brick_project_is_not_refused()
    {
        // The strictness must cost nothing to the shape the CLI scaffold emits, or it is just a
        // new way to fail an author who did nothing wrong.
        Write("Brick.cs", "public sealed class DemoBrick { }");
        WriteProject("""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
              <ItemGroup>
                <PackageReference Include="Ashlar.Brick.Contracts" Version="0.1.1" />
                <PackageReference Include="Ashlar.Authoring" Version="0.1.1" />
              </ItemGroup>
            </Project>
            """);

        var act = () => BrickCertificationProjectLoader.AssertCompileSetIsHashable(Csproj, _dir);

        act.Should().NotThrow();
    }

    [Fact]
    public void Unmanaged_payloads_in_the_build_output_are_not_handed_to_the_compiler()
    {
        // Ashlar.Authoring — one of the two packages a brick may reference, and the one the CLI
        // scaffold emits — drags LLamaSharp's native binaries into runtimes/<rid>/native/. Passing
        // one of those as a metadata reference produces CS0009, and the fence then reported that
        // the CANDIDATE did not compile. The accusation was about source the author had written
        // correctly, for a file the loader itself supplied.
        var buildDir = Path.Combine(_dir, "out");
        var managed = Path.Combine(buildDir, "Brick.dll");
        Directory.CreateDirectory(buildDir);
        File.Copy(typeof(object).Assembly.Location, managed);

        var native = Path.Combine(buildDir, "runtimes", "linux-x64", "native", "libllama.so.dll");
        Directory.CreateDirectory(Path.GetDirectoryName(native)!);
        File.WriteAllBytes(native, [0x7F, 0x45, 0x4C, 0x46, 0x02, 0x01, 0x01, 0x00]);

        // Not under runtimes/, so only the metadata probe can rule it out.
        var strayUnmanaged = Path.Combine(buildDir, "vendor.dll");
        File.WriteAllBytes(strayUnmanaged, [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07]);

        var references = BrickCertificationProjectLoader.CollectReferences(buildDir, managed);

        references.Should().Contain(managed);
        references.Should().NotContain(native, "runtimes/<rid>/native/ is the runtime graph, not the compile graph");
        references.Should().NotContain(strayUnmanaged, "a PE image with no metadata root cannot be a reference wherever it sits");
    }

    [Fact]
    public void Every_managed_assembly_in_the_output_is_still_offered_to_the_compiler()
    {
        // The filter must not become a second bug: dropping a real dependency would make the
        // candidate genuinely fail to compile, which is the accusation this whole change removes.
        var buildDir = Path.Combine(_dir, "out2");
        Directory.CreateDirectory(buildDir);
        var primary = Path.Combine(buildDir, "Brick.dll");
        var dependency = Path.Combine(buildDir, "Ashlar.Authoring.dll");
        File.Copy(typeof(object).Assembly.Location, primary);
        File.Copy(typeof(System.Linq.Enumerable).Assembly.Location, dependency, overwrite: true);

        BrickCertificationProjectLoader.CollectReferences(buildDir, primary)
            .Should().Contain(primary).And.Contain(dependency);
    }

    [Fact]
    public async Task A_reference_the_compiler_cannot_open_blames_the_harness_not_the_candidate()
    {
        // Even with the loader filtering, the fence must never attribute a reference-set failure to
        // the brick author. CS0009 is a statement about the reference set, which the harness owns.
        var junk = Path.Combine(_dir, "not-an-assembly.dll");
        File.WriteAllBytes(junk, [0x7F, 0x45, 0x4C, 0x46, 0x02, 0x01, 0x01, 0x00]);

        var outcome = await new AnalyzerFenceGate().EvaluateAsync(
            MutationProbeBrickSource.Code,
            [typeof(Ashlar.Core.Domain.Bricks.Brick).Assembly.Location, junk]);

        outcome.Passed.Should().BeFalse();
        outcome.FailureReason.Should().NotBeNull();
        outcome.FailureReason!.Should()
            .Contain("harness", "the candidate was never judged, so it must not be the thing accused")
            .And.Contain("CollectReferences", "a refusal that names the wrong component is a refusal that wastes a day");
        outcome.FailureReason.Should().NotContain("candidate does not compile");
    }
}
