<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nexo.VisualVerification\Nexo.VisualVerification.csproj" />
    <ProjectReference Include="..\..\src\Nexo.VisualVerification.Providers\Nexo.VisualVerification.Providers.csproj" />
  </ItemGroup>

</Project>
