namespace Nexo.Feature.Agent.Models
{
    /// <summary>
    /// Represents the response generated by an agent process.
    /// </summary>
    public class AgentResponse
    {
        /// <summary>
        /// Indicates whether the operation represented by the agent's response was successful.
        /// </summary>
        /// <remarks>
        /// A value of <c>true</c> signifies that the operation completed successfully, while
        /// <c>false</c> denotes a failure or an issue during processing.
        /// </remarks>
        public bool Success { get; set; }

        /// <summary>
        /// Gets or sets the content of the response generated by the agent.
        /// </summary>
        /// <remarks>
        /// This property typically contains detailed information or messages resulting from
        /// the agent's processing logic, whether AI-enhanced or standard execution workflows.
        /// </remarks>
        public string Content { get; set; } = string.Empty;
    }
}