<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexo.GeoPrimitives\Nexo.GeoPrimitives.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Vector2.cs" />
    <Compile Remove="Vector3.cs" />
    <Compile Remove="MeshData.cs" />
    <Compile Remove="GeoPoint.cs" />
    <Compile Remove="GeoBounds.cs" />
    <Compile Remove="Latitude.cs" />
    <Compile Remove="Longitude.cs" />
    <Compile Remove="SrtmTileId.cs" />
  </ItemGroup>
</Project>

