using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Nexo.Feature.Analysis.Interfaces;
using Nexo.Feature.Analysis.Models;

namespace Nexo.Feature.Analysis.Services.AgentCodingStandardsIntegration.Operations
{
    public partial class CodeValidationOperations
    {
        private readonly ICodingStandardAnalyzer _analyzer;
        private readonly ILogger _logger;

        public CodeValidationOperations(ICodingStandardAnalyzer analyzer, ILogger logger)
        {
            _analyzer = analyzer ?? throw new ArgumentNullException(nameof(analyzer));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<AgentCodeValidationResult> ValidateAgentGeneratedCodeAsync(
            string agentId,
            string generatedCode,
            string? filePath = null,
            CancellationToken cancellationToken = default)
        {
            _logger.LogInformation("Validating code generated by agent {AgentId}", agentId);
            try
            {
                var validationResult = await _analyzer.ValidateCodeAsync(generatedCode, filePath, agentId, cancellationToken);
                var result = new AgentCodeValidationResult
                {
                    AgentId = agentId,
                    FilePath = filePath,
                    ValidationResult = validationResult,
                    IsValid = validationResult.IsValid,
                    QualityScore = validationResult.Score
                };

                if (!validationResult.IsValid && _analyzer.GetConfiguration().GlobalSettings.AutoFixEnabled)
                {
                    var (fixedCode, appliedFixes) = await _analyzer.AutoFixCodeAsync(generatedCode, filePath, agentId, cancellationToken);
                    result.FixedCode = fixedCode;
                    result.AppliedFixes = appliedFixes;
                    result.WasAutoFixed = appliedFixes.Any();
                    if (result.WasAutoFixed)
                    {
                        var fixedValidationResult = await _analyzer.ValidateCodeAsync(fixedCode, filePath, agentId, cancellationToken);
                        result.FixedValidationResult = fixedValidationResult;
                        result.IsValidAfterFix = fixedValidationResult.IsValid;
                        result.QualityScoreAfterFix = fixedValidationResult.Score;
                    }
                }

                _logger.LogInformation("Code validation completed for agent {AgentId}. Valid: {IsValid}, Score: {Score}", agentId, result.IsValid, result.QualityScore);
                return result;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error validating code generated by agent {AgentId}", agentId);
                return new AgentCodeValidationResult { AgentId = agentId, FilePath = filePath, IsValid = false, QualityScore = 0, ErrorMessage = ex.Message };
            }
        }

        public async Task<Dictionary<string, AgentCodeValidationResult>> ValidateAgentGeneratedCodeFilesAsync(
            string agentId,
            Dictionary<string, string> generatedCodeFiles,
            CancellationToken cancellationToken = default)
        {
            _logger.LogInformation("Validating {FileCount} code files generated by agent {AgentId}", generatedCodeFiles.Count, agentId);
            var results = new Dictionary<string, AgentCodeValidationResult>();
            foreach (var file in generatedCodeFiles)
            {
                var result = await ValidateAgentGeneratedCodeAsync(agentId, file.Value, file.Key, cancellationToken);
                results[file.Key] = result;
            }
            return results;
        }

        public async Task<Dictionary<string, AgentCodeValidationResult>> ValidateCodeArtifactsAsync(
            Dictionary<string, (string Content, string? GeneratedBy)> artifacts,
            CancellationToken cancellationToken = default)
        {
            _logger.LogInformation("Validating {ArtifactCount} code artifacts", artifacts.Count);
            var results = new Dictionary<string, AgentCodeValidationResult>();
            foreach (var artifact in artifacts)
            {
                var result = await ValidateAgentGeneratedCodeAsync(artifact.Value.GeneratedBy ?? "unknown-agent", artifact.Value.Content, artifact.Key, cancellationToken);
                results[artifact.Key] = result;
            }
            return results;
        }
    }
}


