using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Playground.Server.Models;

namespace Playground.Server.Services;

public class LovableDemoService
{
    private readonly List<DemoScenario> _scenarios = new()
    {
        new DemoScenario
        {
            Id = "todo-app",
            Name = "Todo App with Dark Mode",
            Description = "A modern todo application with dark mode, drag-and-drop, and real-time sync",
            Prompt = "Create a todo app with dark mode toggle, drag and drop reordering, real-time sync, and responsive design",
            AppType = "web",
            Features = new[] { "Dark Mode", "Drag & Drop", "Real-time", "Responsive" },
            GeneratedCode = GenerateTodoAppCode(),
            PreviewUrl = "/preview-demo"
        },
        new DemoScenario
        {
            Id = "ecommerce",
            Name = "E-commerce Store",
            Description = "A full-featured online store with product catalog, cart, and checkout",
            Prompt = "Build an e-commerce website with product catalog, shopping cart, user authentication, and payment processing",
            AppType = "web",
            Features = new[] { "Authentication", "Database", "Payment", "Responsive" },
            GeneratedCode = GenerateEcommerceCode(),
            PreviewUrl = "/preview-demo"
        },
        new DemoScenario
        {
            Id = "chat-app",
            Name = "Real-time Chat App",
            Description = "A messaging application with real-time communication and file sharing",
            Prompt = "Create a real-time chat application with message history, file uploads, and online status indicators",
            AppType = "web",
            Features = new[] { "Real-time", "File Upload", "Authentication", "PWA" },
            GeneratedCode = GenerateChatAppCode(),
            PreviewUrl = "/preview-demo"
        },
        new DemoScenario
        {
            Id = "mobile-fitness",
            Name = "Fitness Tracker Mobile App",
            Description = "A mobile fitness tracking app with workout plans and progress charts",
            Prompt = "Develop a mobile fitness app with workout tracking, progress charts, and social features",
            AppType = "mobile",
            Features = new[] { "Mobile", "Charts", "Social", "Offline" },
            GeneratedCode = GenerateMobileFitnessCode(),
            PreviewUrl = "/preview-demo"
        },
        new DemoScenario
        {
            Id = "api-server",
            Name = "REST API Server",
            Description = "A robust API server with authentication, rate limiting, and documentation",
            Prompt = "Build a REST API server with user authentication, rate limiting, data validation, and auto-generated documentation",
            AppType = "api",
            Features = new[] { "Authentication", "Rate Limiting", "Validation", "Documentation" },
            GeneratedCode = GenerateApiServerCode(),
            PreviewUrl = "/preview-demo"
        }
    };

    public async Task<List<DemoScenario>> GetScenariosAsync()
    {
        await Task.Delay(100); // Simulate async operation
        return _scenarios.ToList();
    }

    public async Task<DemoScenario?> GetScenarioAsync(string id)
    {
        await Task.Delay(100);
        return _scenarios.FirstOrDefault(s => s.Id == id);
    }

    public async Task<AppGenerationResult> GenerateAppAsync(string prompt, string appType, List<string> features)
    {
        await Task.Delay(2000); // Simulate AI generation time

        var result = new AppGenerationResult
        {
            Prompt = prompt,
            AppType = appType,
            Features = features,
            GeneratedAt = DateTime.UtcNow,
            Confidence = 0.85 + (new Random().NextDouble() * 0.1), // 85-95% confidence
            GenerationTime = TimeSpan.FromSeconds(2.5 + new Random().NextDouble() * 2)
        };

        // Generate appropriate code based on app type
        result.GeneratedCode = appType switch
        {
            "web" => GenerateWebAppCode(prompt, features),
            "mobile" => GenerateMobileAppCode(prompt, features),
            "desktop" => GenerateDesktopAppCode(prompt, features),
            "api" => GenerateApiCode(prompt, features),
            "game" => GenerateGameCode(prompt, features),
            _ => GenerateWebAppCode(prompt, features)
        };

        result.Files = GenerateFiles(result.GeneratedCode, appType);
        result.PreviewUrl = "/preview-demo";

        return result;
    }

    private static string GenerateTodoAppCode()
    {
        return @"// Todo App - Generated by Nexo
import React, { useState, useEffect } from 'react';
import './TodoApp.css';

const TodoApp = () => {
  const [todos, setTodos] = useState([]);
  const [newTodo, setNewTodo] = useState('');
  const [filter, setFilter] = useState('all');
  const [darkMode, setDarkMode] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('todos');
    if (saved) setTodos(JSON.parse(saved));
  }, []);

  useEffect(() => {
    localStorage.setItem('todos', JSON.stringify(todos));
  }, [todos]);

  const addTodo = () => {
    if (newTodo.trim()) {
      setTodos([...todos, {
        id: Date.now(),
        text: newTodo.trim(),
        completed: false
      }]);
      setNewTodo('');
    }
  };

  const toggleTodo = (id) => {
    setTodos(todos.map(todo =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  const deleteTodo = (id) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  const filteredTodos = todos.filter(todo => {
    if (filter === 'active') return !todo.completed;
    if (filter === 'completed') return todo.completed;
    return true;
  });

  return (
    <div className={`todo-app ${darkMode ? 'dark' : ''}`}>
      <header className='app-header'>
        <h1>📝 Todo App</h1>
        <button 
          className='theme-toggle'
          onClick={() => setDarkMode(!darkMode)}
        >
          {darkMode ? '🌙' : '☀️'}
        </button>
      </header>
      
      <div className='app-body'>
        <div className='add-todo'>
          <input
            type='text'
            value={newTodo}
            onChange={(e) => setNewTodo(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && addTodo()}
            placeholder='Add a new todo...'
            className='todo-input'
          />
          <button onClick={addTodo} className='add-btn'>+</button>
        </div>

        <div className='filters'>
          {['all', 'active', 'completed'].map(f => (
            <button
              key={f}
              className={`filter-btn ${filter === f ? 'active' : ''}`}
              onClick={() => setFilter(f)}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        <div className='todo-list'>
          {filteredTodos.map(todo => (
            <div key={todo.id} className={`todo-item ${todo.completed ? 'completed' : ''}`}>
              <input
                type='checkbox'
                checked={todo.completed}
                onChange={() => toggleTodo(todo.id)}
                className='todo-checkbox'
              />
              <span className='todo-text'>{todo.text}</span>
              <button
                onClick={() => deleteTodo(todo.id)}
                className='delete-btn'
              >
                ×
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default TodoApp;";
    }

    private static string GenerateEcommerceCode()
    {
        return @"// E-commerce Store - Generated by Nexo
import React, { useState, useEffect } from 'react';
import './EcommerceStore.css';

const EcommerceStore = () => {
  const [products, setProducts] = useState([]);
  const [cart, setCart] = useState([]);
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchProducts();
  }, []);

  const fetchProducts = async () => {
    setLoading(true);
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 1000));
    setProducts([
      { id: 1, name: 'Wireless Headphones', price: 99.99, image: '/headphones.jpg' },
      { id: 2, name: 'Smart Watch', price: 199.99, image: '/watch.jpg' },
      { id: 3, name: 'Laptop Stand', price: 49.99, image: '/stand.jpg' }
    ]);
    setLoading(false);
  };

  const addToCart = (product) => {
    setCart([...cart, { ...product, quantity: 1 }]);
  };

  const removeFromCart = (productId) => {
    setCart(cart.filter(item => item.id !== productId));
  };

  const getTotalPrice = () => {
    return cart.reduce((total, item) => total + (item.price * item.quantity), 0);
  };

  if (loading) {
    return <div className='loading'>Loading products...</div>;
  }

  return (
    <div className='ecommerce-store'>
      <header className='store-header'>
        <h1>🛍️ My Store</h1>
        <div className='cart-info'>
          <span>Cart ({cart.length})</span>
          <span>Total: ${getTotalPrice().toFixed(2)}</span>
        </div>
      </header>

      <div className='products-grid'>
        {products.map(product => (
          <div key={product.id} className='product-card'>
            <img src={product.image} alt={product.name} className='product-image' />
            <h3>{product.name}</h3>
            <p className='price'>${product.price}</p>
            <button 
              onClick={() => addToCart(product)}
              className='add-to-cart-btn'
            >
              Add to Cart
            </button>
          </div>
        ))}
      </div>

      {cart.length > 0 && (
        <div className='cart-sidebar'>
          <h3>Shopping Cart</h3>
          {cart.map(item => (
            <div key={item.id} className='cart-item'>
              <span>{item.name}</span>
              <span>${item.price}</span>
              <button onClick={() => removeFromCart(item.id)}>Remove</button>
            </div>
          ))}
          <div className='cart-total'>
            <strong>Total: ${getTotalPrice().toFixed(2)}</strong>
          </div>
        </div>
      )}
    </div>
  );
};

export default EcommerceStore;";
    }

    private static string GenerateChatAppCode()
    {
        return @"// Real-time Chat App - Generated by Nexo
import React, { useState, useEffect, useRef } from 'react';
import './ChatApp.css';

const ChatApp = () => {
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState('');
  const [username, setUsername] = useState('');
  const [isConnected, setIsConnected] = useState(false);
  const messagesEndRef = useRef(null);

  useEffect(() => {
    // Simulate WebSocket connection
    const ws = new WebSocket('ws://localhost:8080/chat');
    
    ws.onopen = () => {
      setIsConnected(true);
      console.log('Connected to chat server');
    };

    ws.onmessage = (event) => {
      const message = JSON.parse(event.data);
      setMessages(prev => [...prev, message]);
    };

    ws.onclose = () => {
      setIsConnected(false);
      console.log('Disconnected from chat server');
    };

    return () => ws.close();
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = () => {
    if (newMessage.trim() && username.trim()) {
      const message = {
        id: Date.now(),
        username,
        text: newMessage.trim(),
        timestamp: new Date().toISOString()
      };
      
      setMessages(prev => [...prev, message]);
      setNewMessage('');
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      sendMessage();
    }
  };

  return (
    <div className='chat-app'>
      <div className='chat-header'>
        <h1>💬 Chat App</h1>
        <div className={`connection-status ${isConnected ? 'connected' : 'disconnected'}`}>
          {isConnected ? '🟢 Online' : '🔴 Offline'}
        </div>
      </div>

      <div className='chat-body'>
        <div className='messages-container'>
          {messages.map(message => (
            <div key={message.id} className='message'>
              <div className='message-header'>
                <span className='username'>{message.username}</span>
                <span className='timestamp'>
                  {new Date(message.timestamp).toLocaleTimeString()}
                </span>
              </div>
              <div className='message-text'>{message.text}</div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        <div className='chat-input'>
          <input
            type='text'
            placeholder='Enter your username...'
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className='username-input'
            disabled={messages.length > 0}
          />
          <input
            type='text'
            placeholder='Type a message...'
            value={newMessage}
            onChange={(e) => setNewMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            className='message-input'
            disabled={!username.trim()}
          />
          <button 
            onClick={sendMessage}
            disabled={!newMessage.trim() || !username.trim()}
            className='send-btn'
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
};

export default ChatApp;";
    }

    private static string GenerateMobileFitnessCode()
    {
        return @"// Mobile Fitness App - Generated by Nexo
import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const FitnessApp = () => {
  const [workouts, setWorkouts] = useState([]);
  const [currentWorkout, setCurrentWorkout] = useState(null);
  const [stats, setStats] = useState({
    totalWorkouts: 0,
    caloriesBurned: 0,
    totalTime: 0
  });

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const savedWorkouts = await AsyncStorage.getItem('workouts');
      const savedStats = await AsyncStorage.getItem('stats');
      
      if (savedWorkouts) setWorkouts(JSON.parse(savedWorkouts));
      if (savedStats) setStats(JSON.parse(savedStats));
    } catch (error) {
      console.error('Error loading data:', error);
    }
  };

  const saveData = async (newWorkouts, newStats) => {
    try {
      await AsyncStorage.setItem('workouts', JSON.stringify(newWorkouts));
      await AsyncStorage.setItem('stats', JSON.stringify(newStats));
    } catch (error) {
      console.error('Error saving data:', error);
    }
  };

  const startWorkout = (workout) => {
    setCurrentWorkout({
      ...workout,
      startTime: new Date(),
      exercises: workout.exercises.map(ex => ({ ...ex, completed: false }))
    });
  };

  const completeExercise = (exerciseId) => {
    if (!currentWorkout) return;

    const updatedWorkout = {
      ...currentWorkout,
      exercises: currentWorkout.exercises.map(ex =>
        ex.id === exerciseId ? { ...ex, completed: true } : ex
      )
    };

    setCurrentWorkout(updatedWorkout);

    // Check if all exercises are completed
    const allCompleted = updatedWorkout.exercises.every(ex => ex.completed);
    if (allCompleted) {
      finishWorkout(updatedWorkout);
    }
  };

  const finishWorkout = (workout) => {
    const endTime = new Date();
    const duration = (endTime - workout.startTime) / 1000 / 60; // minutes

    const completedWorkout = {
      ...workout,
      endTime,
      duration,
      caloriesBurned: workout.exercises.length * 15 // rough estimate
    };

    const newWorkouts = [...workouts, completedWorkout];
    const newStats = {
      totalWorkouts: stats.totalWorkouts + 1,
      caloriesBurned: stats.caloriesBurned + completedWorkout.caloriesBurned,
      totalTime: stats.totalTime + duration
    };

    setWorkouts(newWorkouts);
    setStats(newStats);
    setCurrentWorkout(null);
    saveData(newWorkouts, newStats);
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>💪 Fitness Tracker</Text>
        <Text style={styles.subtitle}>Track your workouts and progress</Text>
      </View>

      <View style={styles.statsContainer}>
        <View style={styles.statItem}>
          <Text style={styles.statNumber}>{stats.totalWorkouts}</Text>
          <Text style={styles.statLabel}>Workouts</Text>
        </View>
        <View style={styles.statItem}>
          <Text style={styles.statNumber}>{stats.caloriesBurned}</Text>
          <Text style={styles.statLabel}>Calories</Text>
        </View>
        <View style={styles.statItem}>
          <Text style={styles.statNumber}>{Math.round(stats.totalTime)}</Text>
          <Text style={styles.statLabel}>Minutes</Text>
        </View>
      </View>

      {currentWorkout ? (
        <View style={styles.currentWorkout}>
          <Text style={styles.workoutTitle}>{currentWorkout.name}</Text>
          {currentWorkout.exercises.map(exercise => (
            <TouchableOpacity
              key={exercise.id}
              style={[
                styles.exerciseItem,
                exercise.completed && styles.exerciseCompleted
              ]}
              onPress={() => completeExercise(exercise.id)}
            >
              <Text style={styles.exerciseName}>{exercise.name}</Text>
              <Text style={styles.exerciseSets}>{exercise.sets} sets</Text>
            </TouchableOpacity>
          ))}
        </View>
      ) : (
        <View style={styles.workoutList}>
          <Text style={styles.sectionTitle}>Available Workouts</Text>
          {workouts.map(workout => (
            <TouchableOpacity
              key={workout.id}
              style={styles.workoutItem}
              onPress={() => startWorkout(workout)}
            >
              <Text style={styles.workoutName}>{workout.name}</Text>
              <Text style={styles.workoutDescription}>{workout.description}</Text>
            </TouchableOpacity>
          ))}
        </View>
      )}
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    padding: 20,
    backgroundColor: '#2196F3',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
  subtitle: {
    fontSize: 16,
    color: 'white',
    opacity: 0.8,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 20,
    backgroundColor: 'white',
    margin: 10,
    borderRadius: 10,
  },
  statItem: {
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2196F3',
  },
  statLabel: {
    fontSize: 14,
    color: '#666',
  },
  // ... more styles
});

export default FitnessApp;";
    }

    private static string GenerateApiServerCode()
    {
        return @"// REST API Server - Generated by Nexo
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const jwt = require('jsonwebtoken');
const bcrypt = require('bcryptjs');
const { body, validationResult } = require('express-validator');

const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';

// Middleware
app.use(helmet());
app.use(cors());
app.use(express.json());

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100 // limit each IP to 100 requests per windowMs
});
app.use(limiter);

// In-memory storage (replace with database in production)
const users = [];
const posts = [];

// Authentication middleware
const authenticateToken = (req, res, next) => {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];

  if (!token) {
    return res.status(401).json({ error: 'Access token required' });
  }

  jwt.verify(token, JWT_SECRET, (err, user) => {
    if (err) {
      return res.status(403).json({ error: 'Invalid token' });
    }
    req.user = user;
    next();
  });
};

// Validation middleware
const validateRequest = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

// Routes

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date().toISOString() });
});

// User registration
app.post('/api/auth/register', [
  body('email').isEmail().normalizeEmail(),
  body('password').isLength({ min: 6 }),
  body('name').trim().isLength({ min: 2 })
], validateRequest, async (req, res) => {
  try {
    const { email, password, name } = req.body;

    // Check if user already exists
    if (users.find(user => user.email === email)) {
      return res.status(400).json({ error: 'User already exists' });
    }

    // Hash password
    const hashedPassword = await bcrypt.hash(password, 10);

    // Create user
    const user = {
      id: users.length + 1,
      email,
      password: hashedPassword,
      name,
      createdAt: new Date()
    };

    users.push(user);

    // Generate JWT
    const token = jwt.sign(
      { userId: user.id, email: user.email },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.status(201).json({
      message: 'User created successfully',
      token,
      user: { id: user.id, email: user.email, name: user.name }
    });
  } catch (error) {
    res.status(500).json({ error: 'Internal server error' });
  }
});

// User login
app.post('/api/auth/login', [
  body('email').isEmail().normalizeEmail(),
  body('password').exists()
], validateRequest, async (req, res) => {
  try {
    const { email, password } = req.body;

    const user = users.find(user => user.email === email);
    if (!user) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    const isValidPassword = await bcrypt.compare(password, user.password);
    if (!isValidPassword) {
      return res.status(401).json({ error: 'Invalid credentials' });
    }

    const token = jwt.sign(
      { userId: user.id, email: user.email },
      JWT_SECRET,
      { expiresIn: '24h' }
    );

    res.json({
      message: 'Login successful',
      token,
      user: { id: user.id, email: user.email, name: user.name }
    });
  } catch (error) {
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Get all posts
app.get('/api/posts', authenticateToken, (req, res) => {
  res.json({
    posts: posts.map(post => ({
      id: post.id,
      title: post.title,
      content: post.content,
      author: post.author,
      createdAt: post.createdAt
    }))
  });
});

// Create new post
app.post('/api/posts', authenticateToken, [
  body('title').trim().isLength({ min: 1, max: 100 }),
  body('content').trim().isLength({ min: 1, max: 1000 })
], validateRequest, (req, res) => {
  const { title, content } = req.body;

  const post = {
    id: posts.length + 1,
    title,
    content,
    author: req.user.name,
    createdAt: new Date()
  };

  posts.push(post);

  res.status(201).json({
    message: 'Post created successfully',
    post: {
      id: post.id,
      title: post.title,
      content: post.content,
      author: post.author,
      createdAt: post.createdAt
    }
  });
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Something went wrong!' });
});

// 404 handler
app.use('*', (req, res) => {
  res.status(404).json({ error: 'Route not found' });
});

app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`📚 API Documentation: http://localhost:${PORT}/api-docs`);
});

module.exports = app;";
    }

    private static string GenerateGameCode()
    {
        return @"// 2D Platformer Game - Generated by Nexo
using UnityEngine;
using UnityEngine.SceneManagement;

public class PlayerController : MonoBehaviour
{
    [SerializeField] private float moveSpeed = 5f;
    [SerializeField] private float jumpForce = 10f;
    [SerializeField] private Transform groundCheck;
    [SerializeField] private LayerMask groundLayer;
    
    private Rigidbody2D rb;
    private bool isGrounded;
    private float horizontalInput;
    private Animator animator;
    private SpriteRenderer spriteRenderer;

    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        spriteRenderer = GetComponent<SpriteRenderer>();
    }

    void Update()
    {
        HandleInput();
        CheckGrounded();
        UpdateAnimations();
    }

    void FixedUpdate()
    {
        Move();
    }

    void HandleInput()
    {
        horizontalInput = Input.GetAxisRaw(""Horizontal"");
        
        if (Input.GetButtonDown(""Jump"") && isGrounded)
        {
            Jump();
        }
    }

    void Move()
    {
        rb.velocity = new Vector2(horizontalInput * moveSpeed, rb.velocity.y);
    }

    void Jump()
    {
        rb.velocity = new Vector2(rb.velocity.x, jumpForce);
    }

    void CheckGrounded()
    {
        isGrounded = Physics2D.OverlapCircle(groundCheck.position, 0.2f, groundLayer);
    }

    void UpdateAnimations()
    {
        animator.SetFloat(""Speed"", Mathf.Abs(horizontalInput));
        animator.SetBool(""IsGrounded"", isGrounded);
        
        if (horizontalInput > 0)
            spriteRenderer.flipX = false;
        else if (horizontalInput < 0)
            spriteRenderer.flipX = true;
    }
}

public class GameManager : MonoBehaviour
{
    [SerializeField] private int score = 0;
    [SerializeField] private int lives = 3;
    [SerializeField] private Text scoreText;
    [SerializeField] private Text livesText;
    [SerializeField] private GameObject gameOverPanel;

    public static GameManager Instance { get; private set; }

    void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }
    }

    void Start()
    {
        UpdateUI();
    }

    public void AddScore(int points)
    {
        score += points;
        UpdateUI();
    }

    public void LoseLife()
    {
        lives--;
        UpdateUI();
        
        if (lives <= 0)
        {
            GameOver();
        }
    }

    void UpdateUI()
    {
        if (scoreText != null)
            scoreText.text = ""Score: "" + score;
        if (livesText != null)
            livesText.text = ""Lives: "" + lives;
    }

    void GameOver()
    {
        Time.timeScale = 0f;
        if (gameOverPanel != null)
            gameOverPanel.SetActive(true);
    }

    public void RestartGame()
    {
        Time.timeScale = 1f;
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void QuitGame()
    {
        Application.Quit();
    }
}

public class Collectible : MonoBehaviour
{
    [SerializeField] private int value = 10;
    [SerializeField] private AudioClip collectSound;

    void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag(""Player""))
        {
            GameManager.Instance.AddScore(value);
            
            if (collectSound != null)
                AudioSource.PlayClipAtPoint(collectSound, transform.position);
            
            Destroy(gameObject);
        }
    }
}";
    }

    private string GenerateWebAppCode(string prompt, List<string> features)
    {
        // Generate web app code based on prompt and features
        return $"// Web App - Generated by Nexo\n// Prompt: {prompt}\n// Features: {string.Join(", ", features)}\n\n" + GenerateTodoAppCode();
    }

    private string GenerateMobileAppCode(string prompt, List<string> features)
    {
        return $"// Mobile App - Generated by Nexo\n// Prompt: {prompt}\n// Features: {string.Join(", ", features)}\n\n" + GenerateMobileFitnessCode();
    }

    private string GenerateDesktopAppCode(string prompt, List<string> features)
    {
        return $"// Desktop App - Generated by Nexo\n// Prompt: {prompt}\n// Features: {string.Join(", ", features)}\n\n" + GenerateTodoAppCode();
    }

    private string GenerateApiCode(string prompt, List<string> features)
    {
        return $"// API Server - Generated by Nexo\n// Prompt: {prompt}\n// Features: {string.Join(", ", features)}\n\n" + GenerateApiServerCode();
    }

    private string GenerateGameCode(string prompt, List<string> features)
    {
        return $"// Game - Generated by Nexo\n// Prompt: {prompt}\n// Features: {string.Join(", ", features)}\n\n" + GenerateGameCode();
    }

    private List<GeneratedFile> GenerateFiles(string code, string appType)
    {
        var files = new List<GeneratedFile>();
        
        switch (appType)
        {
            case "web":
                files.AddRange(new[]
                {
                    new GeneratedFile { FileName = "src/App.js", Content = code },
                    new GeneratedFile { FileName = "src/App.css", Content = "/* Styles generated by Nexo */" },
                    new GeneratedFile { FileName = "package.json", Content = GeneratePackageJson("web") },
                    new GeneratedFile { FileName = "README.md", Content = GenerateReadme("web") }
                });
                break;
            case "mobile":
                files.AddRange(new[]
                {
                    new GeneratedFile { FileName = "src/App.js", Content = code },
                    new GeneratedFile { FileName = "App.js", Content = code },
                    new GeneratedFile { FileName = "package.json", Content = GeneratePackageJson("mobile") },
                    new GeneratedFile { FileName = "android/app/src/main/AndroidManifest.xml", Content = "<!-- Android manifest -->" }
                });
                break;
            case "api":
                files.AddRange(new[]
                {
                    new GeneratedFile { FileName = "server.js", Content = code },
                    new GeneratedFile { FileName = "package.json", Content = GeneratePackageJson("api") },
                    new GeneratedFile { FileName = ".env.example", Content = "JWT_SECRET=your-secret-key\nPORT=3000" },
                    new GeneratedFile { FileName = "README.md", Content = GenerateReadme("api") }
                });
                break;
            case "game":
                files.AddRange(new[]
                {
                    new GeneratedFile { FileName = "Assets/Scripts/PlayerController.cs", Content = code },
                    new GeneratedFile { FileName = "Assets/Scripts/GameManager.cs", Content = code },
                    new GeneratedFile { FileName = "ProjectSettings/ProjectVersion.txt", Content = "m_EditorVersion: 2022.3.0f1" }
                });
                break;
        }

        return files;
    }

    private string GeneratePackageJson(string appType)
    {
        return appType switch
        {
            "web" => @"{
  ""name"": ""nexo-generated-app"",
  ""version"": ""1.0.0"",
  ""description"": ""App generated by Nexo AI platform"",
  ""main"": ""src/App.js"",
  ""scripts"": {
    ""start"": ""react-scripts start"",
    ""build"": ""react-scripts build"",
    ""test"": ""react-scripts test""
  },
  ""dependencies"": {
    ""react"": ""^18.2.0"",
    ""react-dom"": ""^18.2.0"",
    ""react-scripts"": ""5.0.1""
  }
}",
            "mobile" => @"{
  ""name"": ""nexo-mobile-app"",
  ""version"": ""1.0.0"",
  ""description"": ""Mobile app generated by Nexo AI platform"",
  ""main"": ""App.js"",
  ""scripts"": {
    ""start"": ""react-native start"",
    ""android"": ""react-native run-android"",
    ""ios"": ""react-native run-ios""
  },
  ""dependencies"": {
    ""react"": ""^18.2.0"",
    ""react-native"": ""^0.72.0"",
    ""@react-native-async-storage/async-storage"": ""^1.19.0""
  }
}",
            "api" => @"{
  ""name"": ""nexo-api-server"",
  ""version"": ""1.0.0"",
  ""description"": ""API server generated by Nexo AI platform"",
  ""main"": ""server.js"",
  ""scripts"": {
    ""start"": ""node server.js"",
    ""dev"": ""nodemon server.js""
  },
  ""dependencies"": {
    ""express"": ""^4.18.0"",
    ""cors"": ""^2.8.5"",
    ""helmet"": ""^7.0.0"",
    ""express-rate-limit"": ""^6.8.0"",
    ""jsonwebtoken"": ""^9.0.0"",
    ""bcryptjs"": ""^2.4.3"",
    ""express-validator"": ""^7.0.1""
  }
}",
            _ => @"{
  ""name"": ""nexo-generated-project"",
  ""version"": ""1.0.0"",
  ""description"": ""Project generated by Nexo AI platform""
}"
        };
    }

    private string GenerateReadme(string appType)
    {
        return $@"# Nexo Generated {appType.ToUpper()} App

This application was generated by Nexo - Local AI Development Platform.

## Features
- Generated with AI assistance
- Modern development practices
- Ready to run and deploy

## Getting Started

### Prerequisites
- Node.js 16+ (for web/mobile/api apps)
- Unity 2022.3+ (for games)

### Installation
```bash
npm install
```

### Running
```bash
npm start
```

## Generated by Nexo
This app was created using Nexo's AI-powered development platform, running locally on your machine.

Visit [Nexo](/) to learn more about local AI development.";
    }
}

public class DemoScenario
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string Description { get; set; } = "";
    public string Prompt { get; set; } = "";
    public string AppType { get; set; } = "";
    public string[] Features { get; set; } = Array.Empty<string>();
    public string GeneratedCode { get; set; } = "";
    public string PreviewUrl { get; set; } = "";
}

public class AppGenerationResult
{
    public string Prompt { get; set; } = "";
    public string AppType { get; set; } = "";
    public List<string> Features { get; set; } = new();
    public string GeneratedCode { get; set; } = "";
    public List<GeneratedFile> Files { get; set; } = new();
    public string PreviewUrl { get; set; } = "";
    public DateTime GeneratedAt { get; set; }
    public double Confidence { get; set; }
    public TimeSpan GenerationTime { get; set; }
}
