<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexo.Abstractions\Nexo.Abstractions.csproj" />
    <ProjectReference Include="..\Nexo.Brick.Contracts\Nexo.Brick.Contracts.csproj" />
    <ProjectReference Include="..\Nexo.Core\Nexo.Core.csproj" />
    <ProjectReference Include="..\Nexo.Policies\Nexo.Policies.csproj" />
    <ProjectReference Include="..\Nexo.Policies.Dev\Nexo.Policies.Dev.csproj" />
    <ProjectReference Include="..\Nexo.Tools.Assembly\Nexo.Tools.Assembly.csproj" />
    <ProjectReference Include="..\Nexo.Tools.Dev\Nexo.Tools.Dev.csproj" />
  </ItemGroup>

</Project>
