version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: nexollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # Uncomment the following lines if you want to pull specific models on startup
    # command: >
    #   sh -c "ollama serve & 
    #          sleep 10 && 
    #          ollama pull llama3.2:latest && 
    #          wait"

  redis:
    image: redis:7-alpine
    container_name: nexoredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  ollama_data:
  redis_data:

networks:
  default:
    name: nexo-local
