<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NexoCommercialProject>true</NexoCommercialProject>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Nexo.Commercial.Fleet.Contracts/Nexo.Commercial.Fleet.Contracts.csproj" />
    <ProjectReference Include="../Nexo.Commercial.Fleet.Infrastructure/Nexo.Commercial.Fleet.Infrastructure.csproj" />
    <ProjectReference Include="../../../application/src/Nexo.API/Nexo.API.csproj" />
  </ItemGroup>
</Project>
