using Ashlar.Core.Domain.Bricks;
using Ashlar.Core.Domain.Export;
using Ashlar.Core.Domain.Workflows;

namespace Ashlar.Infrastructure.Export;

/// <summary>
/// Content generated by AI.
/// </summary>
public class GeneratedContent
{
    /// <summary>Generated content variations.</summary>
    public IReadOnlyList<GeneratedVariation> Variations { get; init; } = [];
}
