<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Nexo.Core.Domain/Nexo.Core.Domain.csproj" />
    <ProjectReference Include="../../src/Nexo.Shared/Nexo.Shared.csproj" />
    <ProjectReference Include="../../src/Nexo.Feature.Pipeline/Nexo.Feature.Pipeline.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Include="**/*.cs" />
  </ItemGroup>

</Project> 