<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <NullableReferenceTypes>true</NullableReferenceTypes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="AWSSDK.Lambda" />
    <PackageReference Include="AWSSDK.ECS" />
    <PackageReference Include="AWSSDK.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexo.Core.Application\Nexo.Core.Application.csproj" />
    <ProjectReference Include="..\Nexo.Shared\Nexo.Shared.csproj" />
  </ItemGroup>

</Project> 