<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    <AshlarCommercialProject>true</AshlarCommercialProject>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/Ashlar.Core.Application/Ashlar.Core.Application.csproj" />
        <ProjectReference Include="../../../src/Ashlar.Core.Domain/Ashlar.Core.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OsmSharp" />
        <PackageReference Include="NetTopologySuite" />
        <PackageReference Include="NetTopologySuite.IO.VectorTiles" />
        <PackageReference Include="NetTopologySuite.IO.VectorTiles.Mapbox" />
    </ItemGroup>

</Project>
