<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Nexo.NugetOrgRestoreHostingOnly</RootNamespace>
    <NexoPublishedVerifyVersion Condition="'$(NexoPublishedVerifyVersion)' == ''">0.0.0</NexoPublishedVerifyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nexo.Hosting" Version="$(NexoPublishedVerifyVersion)" />
  </ItemGroup>
</Project>
