using System;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;
using System.Collections.Generic;
using System.Linq;
using NexoDirectorStudio.DTO;

namespace NexoDirectorStudio.Game
{
    /// <summary>
    /// Main game controller for the Doom-style FPS game generated by Director Studio.
    /// This script manages the game state, player, enemies, and world interactions.
    /// </summary>
    public class DoomFPSGame : MonoBehaviour
    {
        [Header("Game Configuration")]
        public GamePlan gamePlan;
        public WorldLayout worldLayout;
        public InteractionGraph interactionGraph;
        public ContentBundle contentBundle;
        
        [Header("Player Settings")]
        public float moveSpeed = 5f;
        public float mouseSensitivity = 2f;
        public float jumpForce = 5f;
        
        [Header("Combat Settings")]
        public float fireRate = 0.1f;
        public int maxAmmo = 30;
        public int currentAmmo;
        public int health = 100;
        public int armor = 0;
        
        [Header("Game State")]
        public bool isGameActive = false;
        public float gameTime = 0f;
        public int enemiesKilled = 0;
        public int secretsFound = 0;
        
        // Game Objects
        private Camera playerCamera;
        private CharacterController playerController;
        private List<GameObject> enemies = new List<GameObject>();
        private List<GameObject> weapons = new List<GameObject>();
        private List<GameObject> powerUps = new List<GameObject>();
        
        // Input
        private float mouseX, mouseY;
        private Vector3 moveDirection;
        private bool isJumping;
        private bool isFiring;
        private float lastFireTime;
        
        // UI
        private DoomFPSUI gameUI;
        
        void Start()
        {
            InitializeGame();
        }
        
        void Update()
        {
            if (isGameActive)
            {
                HandleInput();
                UpdateGameState();
                CheckGameConditions();
            }
        }
        
        void InitializeGame()
        {
            Debug.Log("🎮 Initializing Doom-style FPS Game...");
            
            // Initialize player
            InitializePlayer();
            
            // Generate world from layout
            GenerateWorld();
            
            // Spawn enemies and objects
            SpawnGameObjects();
            
            // Initialize UI
            InitializeUI();
            
            // Start the game
            StartGame();
            
            Debug.Log("✅ Doom FPS Game initialized successfully!");
        }
        
        void InitializePlayer()
        {
            // Get player components
            playerCamera = Camera.main;
            playerController = GetComponent<CharacterController>();
            
            // Set initial values
            currentAmmo = maxAmmo;
            health = 100;
            armor = 0;
            
            // Lock cursor for FPS controls
            Cursor.lockState = CursorLockMode.Locked;
            Cursor.visible = false;
            
            Debug.Log("✅ Player initialized");
        }
        
        void GenerateWorld()
        {
            Debug.Log($"🏗️ Generating world: {worldLayout.Dimensions.x}x{worldLayout.Dimensions.y}x{worldLayout.Dimensions.z}");
            
            // Create world geometry from tiles
            foreach (var tile in worldLayout.Tiles)
            {
                CreateTile(tile);
            }
            
            // Set up lighting
            SetupLighting();
            
            // Set up camera
            SetupCamera();
            
            Debug.Log($"✅ World generated with {worldLayout.Tiles.Count} tiles");
        }
        
        void CreateTile(TileData tile)
        {
            // Create tile GameObject
            var tileObj = new GameObject($"Tile_{tile.GridPosition.x}_{tile.GridPosition.y}");
            tileObj.transform.position = tile.WorldPosition;
            
            // Add tile component
            var tileComponent = tileObj.AddComponent<DoomTile>();
            tileComponent.Initialize(tile);
            
            // Set up tile appearance
            var renderer = tileObj.AddComponent<MeshRenderer>();
            var meshFilter = tileObj.AddComponent<MeshFilter>();
            
            // Create appropriate mesh based on tile type
            meshFilter.mesh = CreateTileMesh(tile.TileType);
            
            // Set material
            renderer.material = GetTileMaterial(tile.TileType);
        }
        
        Mesh CreateTileMesh(string tileType)
        {
            var mesh = new Mesh();
            
            switch (tileType)
            {
                case "Wall":
                    mesh = CreateWallMesh();
                    break;
                case "Ground":
                    mesh = CreateGroundMesh();
                    break;
                case "Platform":
                    mesh = CreatePlatformMesh();
                    break;
                case "Hazard":
                    mesh = CreateHazardMesh();
                    break;
                default:
                    mesh = CreateGroundMesh();
                    break;
            }
            
            return mesh;
        }
        
        Material GetTileMaterial(string tileType)
        {
            // Return appropriate material based on tile type
            var material = new Material(Shader.Find("Standard"));
            
            switch (tileType)
            {
                case "Wall":
                    material.color = new Color(0.3f, 0.3f, 0.3f); // Dark gray
                    break;
                case "Ground":
                    material.color = new Color(0.5f, 0.5f, 0.5f); // Gray
                    break;
                case "Platform":
                    material.color = new Color(0.7f, 0.7f, 0.7f); // Light gray
                    break;
                case "Hazard":
                    material.color = Color.red;
                    break;
                default:
                    material.color = Color.white;
                    break;
            }
            
            return material;
        }
        
        Mesh CreateWallMesh()
        {
            var mesh = new Mesh();
            var vertices = new Vector3[]
            {
                new Vector3(0, 0, 0),
                new Vector3(1, 0, 0),
                new Vector3(1, 1, 0),
                new Vector3(0, 1, 0)
            };
            var triangles = new int[] { 0, 1, 2, 0, 2, 3 };
            
            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            
            return mesh;
        }
        
        Mesh CreateGroundMesh()
        {
            var mesh = new Mesh();
            var vertices = new Vector3[]
            {
                new Vector3(0, 0, 0),
                new Vector3(1, 0, 0),
                new Vector3(1, 0, 1),
                new Vector3(0, 0, 1)
            };
            var triangles = new int[] { 0, 1, 2, 0, 2, 3 };
            
            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            
            return mesh;
        }
        
        Mesh CreatePlatformMesh()
        {
            var mesh = new Mesh();
            var vertices = new Vector3[]
            {
                new Vector3(0, 0, 0),
                new Vector3(1, 0, 0),
                new Vector3(1, 0, 1),
                new Vector3(0, 0, 1)
            };
            var triangles = new int[] { 0, 1, 2, 0, 2, 3 };
            
            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            
            return mesh;
        }
        
        Mesh CreateHazardMesh()
        {
            var mesh = new Mesh();
            var vertices = new Vector3[]
            {
                new Vector3(0, 0, 0),
                new Vector3(1, 0, 0),
                new Vector3(1, 0, 1),
                new Vector3(0, 0, 1)
            };
            var triangles = new int[] { 0, 1, 2, 0, 2, 3 };
            
            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            
            return mesh;
        }
        
        void SetupLighting()
        {
            // Set up atmospheric lighting
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
            RenderSettings.ambientSkyColor = new Color(0.1f, 0.1f, 0.2f);
            RenderSettings.ambientEquatorColor = new Color(0.2f, 0.2f, 0.3f);
            RenderSettings.ambientGroundColor = new Color(0.1f, 0.1f, 0.1f);
            
            // Add directional light
            var lightObj = new GameObject("Directional Light");
            var light = lightObj.AddComponent<Light>();
            light.type = LightType.Directional;
            light.color = new Color(0.8f, 0.7f, 0.6f);
            light.intensity = 0.5f;
            lightObj.transform.rotation = Quaternion.Euler(45, 45, 0);
        }
        
        void SetupCamera()
        {
            if (playerCamera != null)
            {
                playerCamera.transform.position = new Vector3(1, 1.6f, 1);
                playerCamera.fieldOfView = 90f;
            }
        }
        
        void SpawnGameObjects()
        {
            Debug.Log($"🎯 Spawning {worldLayout.Objects.Count} game objects...");
            
            foreach (var obj in worldLayout.Objects)
            {
                SpawnObject(obj);
            }
            
            Debug.Log($"✅ Spawned {enemies.Count} enemies, {weapons.Count} weapons, {powerUps.Count} power-ups");
        }
        
        void SpawnObject(ObjectData obj)
        {
            var objGameObject = new GameObject(obj.ObjectType);
            objGameObject.transform.position = obj.Position;
            objGameObject.transform.rotation = obj.Rotation;
            objGameObject.transform.localScale = obj.Scale;
            
            switch (obj.ObjectType)
            {
                case "EnemySpawn":
                    SpawnEnemy(objGameObject);
                    break;
                case "Weapon":
                    SpawnWeapon(objGameObject);
                    break;
                case "PowerUp":
                    SpawnPowerUp(objGameObject);
                    break;
                case "SpawnPoint":
                    SetPlayerSpawn(objGameObject);
                    break;
                case "Goal":
                    SetGoal(objGameObject);
                    break;
            }
        }
        
        void SpawnEnemy(GameObject obj)
        {
            enemies.Add(obj);
            var enemy = obj.AddComponent<DoomEnemy>();
            enemy.Initialize();
        }
        
        void SpawnWeapon(GameObject obj)
        {
            weapons.Add(obj);
            var weapon = obj.AddComponent<DoomWeapon>();
            weapon.Initialize();
        }
        
        void SpawnPowerUp(GameObject obj)
        {
            powerUps.Add(obj);
            var powerUp = obj.AddComponent<DoomPowerUp>();
            powerUp.Initialize();
            
            // Register with InteractionBus
            RegisterInteraction(powerUp);
        }
        
        void SetPlayerSpawn(GameObject obj)
        {
            transform.position = obj.transform.position;
        }
        
        void SetGoal(GameObject obj)
        {
            var goal = obj.AddComponent<DoomGoal>();
            goal.Initialize();
            
            // Register with InteractionBus
            RegisterInteraction(goal);
        }
        
        void InitializeUI()
        {
            // Create UI GameObject
            var uiObj = new GameObject("Game UI");
            gameUI = uiObj.AddComponent<DoomFPSUI>();
            gameUI.Initialize(this);
        }
        
        void StartGame()
        {
            isGameActive = true;
            gameTime = 0f;
            Debug.Log("🚀 Doom FPS Game started!");
        }
        
        void HandleInput()
        {
            // Mouse look
            mouseX += Input.GetAxis("Mouse X") * mouseSensitivity;
            mouseY -= Input.GetAxis("Mouse Y") * mouseSensitivity;
            mouseY = Mathf.Clamp(mouseY, -90f, 90f);
            
            playerCamera.transform.rotation = Quaternion.Euler(mouseY, mouseX, 0);
            
            // Movement
            float horizontal = Input.GetAxis("Horizontal");
            float vertical = Input.GetAxis("Vertical");
            
            moveDirection = transform.right * horizontal + transform.forward * vertical;
            moveDirection = moveDirection.normalized * moveSpeed;
            
            // Jumping
            if (Input.GetButtonDown("Jump") && playerController.isGrounded)
            {
                isJumping = true;
            }
            
            // Firing
            isFiring = Input.GetButton("Fire1");
        }
        
        void UpdateGameState()
        {
            // Move player
            if (playerController.isGrounded)
            {
                moveDirection.y = 0f;
            }
            
            if (isJumping)
            {
                moveDirection.y = jumpForce;
                isJumping = false;
            }
            
            moveDirection.y += Physics.gravity.y * Time.deltaTime;
            playerController.Move(moveDirection * Time.deltaTime);
            
            // Handle firing
            if (isFiring && Time.time - lastFireTime > fireRate && currentAmmo > 0)
            {
                FireWeapon();
                lastFireTime = Time.time;
                currentAmmo--;
            }
            
            // Update game time
            gameTime += Time.deltaTime;
        }
        
        void FireWeapon()
        {
            Debug.Log("🔫 Firing weapon!");
            
            // Raycast for hit detection
            Ray ray = playerCamera.ScreenPointToRay(new Vector3(Screen.width / 2, Screen.height / 2, 0));
            RaycastHit hit;
            
            if (Physics.Raycast(ray, out hit))
            {
                var enemy = hit.collider.GetComponent<DoomEnemy>();
                if (enemy != null)
                {
                    enemy.TakeDamage(25);
                    if (enemy.IsDead())
                    {
                        enemiesKilled++;
                        Debug.Log($"💀 Enemy killed! Total: {enemiesKilled}");
                    }
                }
            }
        }
        
        void CheckGameConditions()
        {
            // Check if player is dead
            if (health <= 0)
            {
                GameOver();
            }
            
            // Check if all enemies are dead
            if (enemies.All(e => e.GetComponent<DoomEnemy>().IsDead()))
            {
                Victory();
            }
            
            // Check time limit
            if (gameTime >= gamePlan.EstimatedDurationMinutes * 60)
            {
                TimeUp();
            }
        }
        
        void GameOver()
        {
            isGameActive = false;
            Debug.Log("💀 Game Over! You died!");
            gameUI.ShowGameOver();
        }
        
        public void Victory()
        {
            isGameActive = false;
            Debug.Log("🎉 Victory! All enemies defeated!");
            gameUI.ShowVictory();
        }
        
        void TimeUp()
        {
            isGameActive = false;
            Debug.Log("⏰ Time's up! Mission failed!");
            gameUI.ShowTimeUp();
        }
        
        public void TakeDamage(int damage)
        {
            if (armor > 0)
            {
                armor -= damage;
                if (armor < 0)
                {
                    health += armor;
                    armor = 0;
                }
            }
            else
            {
                health -= damage;
            }
            
            Debug.Log($"💔 Health: {health}, Armor: {armor}");
        }
        
        public void AddHealth(int amount)
        {
            health = Mathf.Min(100, health + amount);
            Debug.Log($"❤️ Health restored! Health: {health}");
        }
        
        public void AddArmor(int amount)
        {
            armor = Mathf.Min(100, armor + amount);
            Debug.Log($"🛡️ Armor added! Armor: {armor}");
        }
        
        public void AddAmmo(int amount)
        {
            currentAmmo = Mathf.Min(maxAmmo, currentAmmo + amount);
            Debug.Log($"🔫 Ammo added! Ammo: {currentAmmo}");
        }
        
        /// <summary>
        /// Register an interaction with the InteractionBus
        /// </summary>
        private void RegisterInteraction(IInteraction interaction)
        {
            if (interaction == null) return;
            
            // Ensure InteractionBus exists
            var bus = Object.FindFirstObjectByType<InteractionBus>();
            if (bus == null)
            {
                var busGO = new GameObject("InteractionBus");
                bus = busGO.AddComponent<InteractionBus>();
            }
            
            // Register the interaction
            bus.Register(interaction);
        }
    }
}
