<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Storage.Common" />
    <PackageReference Include="Azure.ResourceManager.Storage" />
    <PackageReference Include="Azure.ResourceManager.ContainerService" />
    <PackageReference Include="Azure.ResourceManager.AppService" />
    <PackageReference Include="Azure.ResourceManager.Resources" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Nexo.Core.Application/Nexo.Core.Application.csproj" />
    <ProjectReference Include="../Nexo.Core.Domain/Nexo.Core.Domain.csproj" />
    <ProjectReference Include="../Nexo.Shared/Nexo.Shared.csproj" />
  </ItemGroup>

</Project> 