using System.Globalization;
using System.Text;
using Nexo.GeoTerrain;

namespace Nexo.Adapters.GeoTerrain.Export;

/// <summary>
/// Basic USD writer for mesh data.
/// Generates USD ASCII format (Pixar Universal Scene Description).
/// </summary>
public static class UsdWriter
{
    public static string Write(MeshData mesh, string meshName = "TerrainMesh", string stagePath = "/World")
    {
#if NET8_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(mesh);
#else
        if (mesh is null) throw new ArgumentNullException(nameof(mesh));
#endif
        if (mesh.Vertices is null) throw new ArgumentException("MeshData.Vertices must be non-null.", nameof(mesh));
        if (mesh.Indices is null) throw new ArgumentException("MeshData.Indices must be non-null.", nameof(mesh));

        var sb = new StringBuilder(capacity: mesh.Vertices.Count * 64);
        var inv = CultureInfo.InvariantCulture;

        // USD Header
        sb.AppendLine("#usda 1.0");
        sb.AppendLine("(");
        sb.AppendLine("    doc = \"Generated by Nexo.Adapters.GeoTerrain\"");
        sb.AppendLine("    defaultPrim = \"").Append(meshName).AppendLine("\"");
        sb.AppendLine(")");
        sb.AppendLine();

        // Stage metadata
        sb.AppendLine("def Xform \"").Append(stagePath).AppendLine("\"");
        sb.AppendLine("{");
        sb.AppendLine("    def Mesh \"").Append(meshName).AppendLine("\"");
        sb.AppendLine("    {");

        // Points (vertices)
        sb.Append("        point3f[] points = [");
        for (var i = 0; i < mesh.Vertices.Count; i++)
        {
            var v = mesh.Vertices[i];
            sb.Append("(").Append(v.X.ToString("G9", inv)).Append(", ")
              .Append(v.Y.ToString("G9", inv)).Append(", ")
              .Append(v.Z.ToString("G9", inv)).Append(")");
            if (i < mesh.Vertices.Count - 1) sb.Append(", ");
        }
        sb.AppendLine("]");

        // Face Vertex Indices
        sb.Append("        int[] faceVertexIndices = [");
        for (var i = 0; i < mesh.Indices.Count; i++)
        {
            sb.Append(mesh.Indices[i]);
            if (i < mesh.Indices.Count - 1) sb.Append(", ");
        }
        sb.AppendLine("]");

        // Face Vertex Counts (all triangles = 3)
        sb.Append("        int[] faceVertexCounts = [");
        var triangleCount = mesh.Indices.Count / 3;
        for (var i = 0; i < triangleCount; i++)
        {
            sb.Append("3");
            if (i < triangleCount - 1) sb.Append(", ");
        }
        sb.AppendLine("]");

        // Normals
        if (mesh.Normals != null && mesh.Normals.Count == mesh.Vertices.Count)
        {
            sb.Append("        normal3f[] normals = [");
            for (var i = 0; i < mesh.Normals.Count; i++)
            {
                var n = mesh.Normals[i];
                sb.Append("(").Append(n.X.ToString("G9", inv)).Append(", ")
                  .Append(n.Y.ToString("G9", inv)).Append(", ")
                  .Append(n.Z.ToString("G9", inv)).Append(")");
                if (i < mesh.Normals.Count - 1) sb.Append(", ");
            }
            sb.AppendLine("]");
            sb.AppendLine("        normal3f[] primvars:normals = []");
        }

        // UVs
        if (mesh.TexCoords != null && mesh.TexCoords.Count == mesh.Vertices.Count)
        {
            sb.Append("        float2[] primvars:st = [");
            for (var i = 0; i < mesh.TexCoords.Count; i++)
            {
                var t = mesh.TexCoords[i];
                sb.Append("(").Append(t.X.ToString("G9", inv)).Append(", ")
                  .Append(t.Y.ToString("G9", inv)).Append(")");
                if (i < mesh.TexCoords.Count - 1) sb.Append(", ");
            }
            sb.AppendLine("]");
            sb.AppendLine("        string primvars:st:interpolation = \"vertex\"");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
