namespace Nexo.Core.Domain.Export;

/// <summary>
/// Result of exporting a workflow.
/// </summary>
public class ExportResult
{
    public bool Success { get; init; }
    public ExportMode Mode { get; init; }
    public ExportTarget Target { get; init; }
    
    /// <summary>
    /// Generated files.
    /// </summary>
    public IReadOnlyList<ExportedFile> Files { get; init; } = [];
    
    /// <summary>
    /// For AIGeneratedThenDeterministic: what content was generated.
    /// </summary>
    public GenerationSummary? GenerationSummary { get; init; }
    
    /// <summary>
    /// Runtime requirements (if any).
    /// </summary>
    public IReadOnlyList<string> RuntimeRequirements { get; init; } = [];
    
    /// <summary>
    /// Warnings or notes.
    /// </summary>
    public IReadOnlyList<string> Messages { get; init; } = [];
}

/// <summary>
/// A file generated during export.
/// </summary>
public class ExportedFile
{
    public string Path { get; init; } = default!;
    public string Content { get; init; } = default!;
    public string Language { get; init; } = default!;
}

/// <summary>
/// Summary of AI generation during export.
/// </summary>
public class GenerationSummary
{
    public int ItemsGenerated { get; init; }
    public int VariationsCreated { get; init; }
    public IReadOnlyList<GeneratedItem> Items { get; init; } = [];
}

/// <summary>
/// An item generated by AI during export.
/// </summary>
public class GeneratedItem
{
    public string BrickId { get; init; } = default!;
    public string ItemType { get; init; } = default!;
    public int VariationCount { get; init; }
    public bool Reviewed { get; init; }
}

