using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.InputSystem;
using NexoDoomGame;

namespace NexoDoomGame.Tests
{
    /// <summary>
    /// Edit mode tests for individual components generated by Nexo agents
    /// </summary>
    public partial class ComponentTests
    {
        [Test]
        public void FPSController_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestPlayer");
            var fpsController = gameObject.AddComponent<FPSController>();
            
            // Act & Assert
            Assert.IsNotNull(fpsController, "FPSController component should be present");
            
            // Check for required components
            var characterController = gameObject.GetComponent<CharacterController>();
            Assert.IsNotNull(characterController, "CharacterController should be present");
            
            var camera = gameObject.GetComponentInChildren<Camera>();
            Assert.IsNotNull(camera, "Camera should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void WeaponSystem_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestWeapon");
            var weaponSystem = gameObject.AddComponent<WeaponSystem>();
            
            // Act & Assert
            Assert.IsNotNull(weaponSystem, "WeaponSystem component should be present");
            
            // Check for required components
            var audioSource = gameObject.GetComponent<AudioSource>();
            Assert.IsNotNull(audioSource, "AudioSource should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void EnemyAI_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestEnemy");
            var enemyAI = gameObject.AddComponent<EnemyAI>();
            
            // Act & Assert
            Assert.IsNotNull(enemyAI, "EnemyAI component should be present");
            
            // Check for required components
            var navMeshAgent = gameObject.GetComponent<UnityEngine.AI.NavMeshAgent>();
            Assert.IsNotNull(navMeshAgent, "NavMeshAgent should be present");
            
            var collider = gameObject.GetComponent<Collider>();
            Assert.IsNotNull(collider, "Collider should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void HealthSystem_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestHealth");
            var healthSystem = gameObject.AddComponent<HealthSystem>();
            
            // Act & Assert
            Assert.IsNotNull(healthSystem, "HealthSystem component should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void AudioManager_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestAudio");
            var audioManager = gameObject.AddComponent<AudioManager>();
            
            // Act & Assert
            Assert.IsNotNull(audioManager, "AudioManager component should be present");
            
            // Check for required components
            var audioSource = gameObject.GetComponent<AudioSource>();
            Assert.IsNotNull(audioSource, "AudioSource should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void UIManager_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestUI");
            var uiManager = gameObject.AddComponent<UIManager>();
            
            // Act & Assert
            Assert.IsNotNull(uiManager, "UIManager component should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void GameManager_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestGame");
            var gameManager = gameObject.AddComponent<GameManager>();
            
            // Act & Assert
            Assert.IsNotNull(gameManager, "GameManager component should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void PlayerController_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestPlayer");
            var playerController = gameObject.AddComponent<PlayerController>();
            
            // Act & Assert
            Assert.IsNotNull(playerController, "PlayerController component should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void EnemySpawner_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestSpawner");
            var enemySpawner = gameObject.AddComponent<EnemySpawner>();
            
            // Act & Assert
            Assert.IsNotNull(enemySpawner, "EnemySpawner component should be present");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
        
        [Test]
        public void PickupSystem_ShouldHaveRequiredComponents()
        {
            // Arrange
            var gameObject = new GameObject("TestPickup");
            var pickupSystem = gameObject.AddComponent<PickupSystem>();
            
            // Act & Assert
            Assert.IsNotNull(pickupSystem, "PickupSystem component should be present");
            
            // Check for required components
            var collider = gameObject.GetComponent<Collider>();
            Assert.IsNotNull(collider, "Collider should be present");
            Assert.IsTrue(collider.isTrigger, "Collider should be a trigger");
            
            // Cleanup
            Object.DestroyImmediate(gameObject);
        }
    }
}
