using System.Collections.Concurrent;
using Microsoft.Extensions.Logging;
using Nexo.Orchestration.Agents;
using Nexo.Abstractions.Agents;

namespace Nexo.Orchestration.Coordination;

/// <summary>
/// Summary of overall progress across all agents.
/// 
/// Contains:
/// - Agent counts by state (total, completed, failed, executing, waiting, ready)
/// - Progress percentage
/// - Stalling and thrashing agent counts
/// - Average execution time
/// 
/// Generated by ProgressTracker.GetSummary() for reporting and monitoring.
/// </summary>
public sealed record ProgressSummary
{
    /// <summary>Total number of tracked agents.</summary>
    public int TotalAgents { get; init; }

    /// <summary>Agents that finished successfully.</summary>
    public int Completed { get; init; }

    /// <summary>Agents that failed execution.</summary>
    public int Failed { get; init; }

    /// <summary>Agents currently executing.</summary>
    public int Executing { get; init; }

    /// <summary>Agents blocked waiting on dependencies.</summary>
    public int WaitingForDependencies { get; init; }

    /// <summary>Agents ready to execute.</summary>
    public int Ready { get; init; }

    /// <summary>Overall completion percentage across agents.</summary>
    public double ProgressPercentage { get; init; }

    /// <summary>Agents with no recent progress updates.</summary>
    public int StallingAgents { get; init; }

    /// <summary>Agents cycling rapidly between states.</summary>
    public int ThrashingAgents { get; init; }

    /// <summary>Mean execution time for completed agents.</summary>
    public TimeSpan? AverageExecutionTime { get; init; }
}
