using System.Collections.Concurrent;
using Microsoft.Extensions.Logging;
using Nexo.Orchestration.Agents;
using Nexo.Orchestration.Architect;
using Nexo.Orchestration.Architect.Models;

namespace Nexo.Orchestration.Coordination;

/// <summary>
/// Resource usage report containing current resource utilization statistics.
/// 
/// Contains:
/// - Total allocated resources (compute, context, memory)
/// - Maximum available resources
/// - Utilization percentages for each resource type
/// 
/// Generated by ResourceAllocator.GetUsageReport() for monitoring and reporting.
/// </summary>
public sealed record ResourceUsageReport
{
    /// <summary>Total compute seconds currently allocated.</summary>
    public int TotalAllocatedComputeSeconds { get; init; }

    /// <summary>Total context tokens currently allocated.</summary>
    public int TotalAllocatedContextTokens { get; init; }

    /// <summary>Total memory in megabytes currently allocated.</summary>
    public int TotalAllocatedMemoryMB { get; init; }

    /// <summary>Maximum available compute seconds, if capped.</summary>
    public int? MaxComputeSeconds { get; init; }

    /// <summary>Maximum available context tokens, if capped.</summary>
    public int? MaxContextTokens { get; init; }

    /// <summary>Maximum available memory in megabytes, if capped.</summary>
    public int? MaxMemoryMB { get; init; }

    /// <summary>Compute utilization as a fraction of capacity.</summary>
    public double UtilizationCompute { get; init; }

    /// <summary>Context token utilization as a fraction of capacity.</summary>
    public double UtilizationContext { get; init; }

    /// <summary>Memory utilization as a fraction of capacity.</summary>
    public double UtilizationMemory { get; init; }
}
