<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexo.Core.Domain\Nexo.Core.Domain.csproj" />
    <ProjectReference Include="..\Nexo.Core.Application\Nexo.Core.Application.csproj" />
    <ProjectReference Include="..\Nexo.Abstractions\Nexo.Abstractions.csproj" />
    <ProjectReference Include="..\Nexo.Infrastructure\Nexo.Infrastructure.csproj" />
    <ProjectReference Include="..\Nexo.GeoPrimitives\Nexo.GeoPrimitives.csproj" />
    <ProjectReference Include="..\Nexo.GeoVector\Nexo.GeoVector.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

</Project>
