<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup Condition="
    '$(MSBuildProjectName)' == 'HelloBrick' OR
    '$(MSBuildProjectName)' == 'Nexo.Certified.DamageResolver'
    ">
    <Compile Include="$(MSBuildThisFileDirectory)../build/GlobalUsings.DomainBrick.cs" Link="GlobalUsings.DomainBrick.cs" />
  </ItemGroup>
</Project>
