namespace Ashlar.CLI.Commands.Workflow;

internal sealed record WorkflowStressRunRecord(
    string RunId,
    string GitSha,
    string SpecHash,
    string ProviderSnapshot,
    string ScenarioId,
    string RequestId,
    string CompositionId,
    string ModelProfileId,
    int Iteration,
    bool Success,
    int AgentCount,
    int ConflictCount,
    int EscalationCount,
    long ElapsedMs,
    double Score,
    string Summary,
    string FailureCategory = "none",
    bool Skipped = false,
    DateTimeOffset StartedAtUtc = default,
    long CpuTimeDeltaMs = 0,
    long WorkingSetMb = 0,
    long PrivateMemoryMb = 0,
    long ManagedMemoryMb = 0,
    int ThreadCount = 0,
    string HardwareProfile = "unknown",
    string BenchmarkSet = "workflow-lab");
