<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NexoCommercialProject>true</NexoCommercialProject>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Nexo.Commercial.MeshDirector/Nexo.Commercial.MeshDirector.csproj" />
  </ItemGroup>
</Project>
