<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NexoCommercialProject>true</NexoCommercialProject>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Nexo.Samples.ForgeMapHost</RootNamespace>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Nexo.Commercial.GameDomain/Nexo.Commercial.GameDomain.csproj" />
  </ItemGroup>

</Project>
