<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NexoCommercialProject>true</NexoCommercialProject>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nexo.Commercial.Tests.MeshDirector" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
