using UnityEngine;

/// <summary>
/// Demo script for Iteration 2
/// Generated by Nexo iterative game development pipeline
/// </summary>
public class Iteration2Demo : MonoBehaviour
{
    [SerializeField] private string iterationInfo = "Iteration 2 - Generated by Nexo";
    
    void Start()
    {
        Debug.Log($"Iteration 2 Demo Started");
        Debug.Log("This script was generated by the iterative game development pipeline");
    }
    
    void Update()
    {
        // Demo script - visible in Unity editor
    }
}
