<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Nexo.Core.Application/Nexo.Core.Application.csproj" />
        <ProjectReference Include="../Nexo.Core.Domain/Nexo.Core.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OsmSharp" />
        <PackageReference Include="NetTopologySuite" />
        <PackageReference Include="NetTopologySuite.IO.VectorTiles" />
        <PackageReference Include="NetTopologySuite.IO.VectorTiles.Mapbox" />
    </ItemGroup>

</Project>
