#!/usr/bin/env bash
# Resolve public image digests and write opensource.deps.lock.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/opensource.deps.lock}"
OLLAMA_REF="${OLLAMA_REF:-ollama/ollama:latest}"
DOCKER_REF="${DOCKER_REF:-docker:27-cli}"
UBUNTU_REF="${UBUNTU_REF:-ubuntu:26.04}"
MODEL="${OLLAMA_MODEL:-qwen2.5-coder:3b}"

resolve() {
  local ref="$1" digest
  if ! docker image inspect "$ref" >/dev/null 2>&1; then
    docker pull "$ref" >/dev/null
  fi
  digest="$(docker image inspect "$ref" --format '{{index .RepoDigests 0}}' 2>/dev/null || true)"
  if [ -n "$digest" ] && [[ "$digest" == *@sha256:* ]]; then
    printf '%s\n' "$digest"
  else
    # Fallback when the engine has no registry digest yet.
    printf '%s\n' "$ref"
  fi
}

ollama="$(resolve "$OLLAMA_REF")"
cli="$(resolve "$DOCKER_REF")"
ubuntu="$(resolve "$UBUNTU_REF")"

cat >"$OUT" <<EOF
# Open-source runtime dependencies for the extractor SKU.
# Regenerated by: bash scripts/create-opensource-deps-lock.sh
# Applied by:     bash scripts/pull-opensource-deps.sh
#
# Bespoke images (agent/tool) are NOT listed here - see deployment.release.lock.
OLLAMA_IMAGE=$ollama
DOCKER_CLI_IMAGE=$cli
UBUNTU_IMAGE=$ubuntu
OLLAMA_MODEL=$MODEL
OPENSOURCE_DEPS_KIND=mixed-digest
EOF
echo "Wrote $OUT"
cat "$OUT"
