namespace Ashlar.Core.Domain.Export;

/// <summary>
/// An item generated by AI during export.
/// </summary>
public class GeneratedItem
{
    /// <summary>Brick that produced this generated item.</summary>
    public string BrickId { get; init; } = default!;

    /// <summary>Logical item type label (e.g. template, rule, dataset).</summary>
    public string ItemType { get; init; } = default!;

    /// <summary>Number of AI-generated variations created for this item.</summary>
    public int VariationCount { get; init; }

    /// <summary>Whether an operator reviewed and approved the generated content.</summary>
    public bool Reviewed { get; init; }
}
