using Nexo.Core.Domain.Bricks;
using Nexo.Core.Domain.Export;
using Nexo.Core.Domain.Workflows;

namespace Nexo.Infrastructure.Export;

/// <summary>
/// Content generated by AI.
/// </summary>
public class GeneratedContent
{
    /// <summary>Generated content variations.</summary>
    public IReadOnlyList<GeneratedVariation> Variations { get; init; } = [];
}
