using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Nexo.Feature.AI.Models;

namespace Nexo.Infrastructure.Services.AI.LlamaNative.Providers
{
    public partial class TextGenerationProvider
    {
        private readonly ILogger<TextGenerationProvider> _logger;

        public TextGenerationProvider(ILogger<TextGenerationProvider> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<ModelResponse> GenerateTextAsync(TextGenerationRequest request, CancellationToken cancellationToken)
        {
            try
            {
                _logger.LogInformation("Generating text with Llama: {PromptLength} characters", request.Prompt.Length);

                // Simulate Llama text generation
                await Task.Delay(800, cancellationToken);

                var response = new ModelResponse
                {
                    Success = true,
                    GeneratedText = GenerateLlamaText(request.Prompt),
                    TokensUsed = EstimateTokens(request.Prompt),
                    Model = request.Model ?? "llama-2-7b-chat",
                    FinishReason = "stop"
                };

                return response;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating text with Llama");
                return new ModelResponse
                {
                    Success = false,
                    Error = $"Text generation failed: {ex.Message}"
                };
            }
        }

        private string GenerateLlamaText(string prompt)
        {
            // Simulate Llama-specific text generation
            if (prompt.Contains("story"))
            {
                return "Once upon a time, in a mystical realm where ancient magic flowed through the very air, there lived a brave knight who embarked on an epic quest to save the kingdom from an ancient dragon that had been awakened from its thousand-year slumber.";
            }
            else if (prompt.Contains("explain"))
            {
                return "Llama models are large language models developed by Meta AI. They are designed to understand and generate human-like text based on the input provided. These models use transformer architecture and are trained on vast amounts of text data to understand context, grammar, and meaning.";
            }
            else if (prompt.Contains("code"))
            {
                return "Here's a simple Python function that demonstrates basic programming concepts:\n\ndef greet_user(name):\n    \"\"\"Greet a user with a personalized message.\"\"\"\n    return f\"Hello, {name}! Welcome to the world of programming.\"\n\n# Example usage\nprint(greet_user(\"Alice\"))";
            }
            else
            {
                return "This is a response generated by the Llama model. Llama models are designed to provide helpful, accurate, and contextually appropriate responses to a wide variety of prompts and questions.";
            }
        }

        private int EstimateTokens(string text)
        {
            // Llama models typically use a different tokenization than GPT
            // Rough estimation: 1 token ≈ 3.5 characters for Llama
            return (int)Math.Ceiling(text.Length / 3.5);
        }
    }
}
