namespace Nexo.Demo.Tests.Support;

/// <summary>
/// Output generation functionality for demo harness.
/// </summary>
public static partial class DemoHarness
{
    /// <summary>
    /// Generates scenario outputs based on mode and provider
    /// </summary>
    private static async Task GenerateScenarioOutputs(
        string scenarioPath,
        string outputDir,
        string mode,
        string provider,
        List<string> logs,
        Dictionary<string, double> metrics)
    {
        var outputsDir = Path.Combine(outputDir, "outputs");
        Directory.CreateDirectory(outputsDir);

        switch (mode)
        {
            case "off":
                await GenerateOffModeOutputs(outputsDir, logs, metrics);
                break;
            case "assist":
                await GenerateAssistModeOutputs(outputsDir, logs, metrics);
                break;
            case "hybrid":
                await GenerateHybridModeOutputs(outputsDir, provider, logs, metrics);
                break;
            case "embedded":
                await GenerateEmbeddedModeOutputs(outputsDir, provider, logs, metrics);
                break;
        }
    }

    private static async Task GenerateOffModeOutputs(string outputsDir, List<string> logs, Dictionary<string, double> metrics)
    {
        logs.Add("Generating deterministic offline outputs");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "labels.csv"), 
            "id,label,confidence\n1,urgent,0.95\n2,normal,0.87\n3,low,0.72");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "summary.txt"), 
            "This is a deterministic summary generated offline.");
        metrics["tokens_processed"] = 100;
    }

    private static async Task GenerateAssistModeOutputs(string outputsDir, List<string> logs, Dictionary<string, double> metrics)
    {
        logs.Add("Generating scaffold outputs (no runtime AI)");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "generated_recipe.yaml"), 
            "recipe: generated\nblocks: [triage, summarize]");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "generated_test.cs"), 
            "// Generated test code");
        await GenerateOffModeOutputs(outputsDir, logs, metrics);
        metrics["scaffold_generated"] = 1;
    }

    private static async Task GenerateHybridModeOutputs(string outputsDir, string provider, List<string> logs, Dictionary<string, double> metrics)
    {
        logs.Add($"Generating hybrid outputs with {provider} provider");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "labels.csv"), 
            "id,label,confidence\n1,urgent,0.94\n2,normal,0.88\n3,low,0.71");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "summary.txt"), 
            $"This is a summary generated by local {provider} AI.");
        metrics["tokens_processed"] = 150;
    }

    private static async Task GenerateEmbeddedModeOutputs(string outputsDir, string provider, List<string> logs, Dictionary<string, double> metrics)
    {
        logs.Add($"Generating embedded outputs with {provider} provider");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "labels.csv"), 
            "id,label,confidence\n1,urgent,0.93\n2,normal,0.89\n3,low,0.70");
        await File.WriteAllTextAsync(Path.Combine(outputsDir, "summary.txt"), 
            $"This is a summary generated by cloud {provider} AI.");
        metrics["tokens_processed"] = 200;
        IncrementNetworkAttempts(); // Simulate network call
    }
}
