<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexo.Core.Application\Nexo.Core.Application.csproj" />
    <ProjectReference Include="..\Nexo.Infrastructure\Nexo.Infrastructure.csproj" />
    <ProjectReference Include="..\Nexo.Tests.Application\Nexo.Tests.Application.csproj" />
  </ItemGroup>

</Project>

