namespace Nexo.Orchestration.Playtest.Models;

/// <summary>
/// A balance issue identified from playtest analysis.
/// 
/// Contains:
/// - Issue identification, category, and severity
/// - Title and description
/// - Statistical evidence supporting the issue
/// - Suggested fixes from AI analysis
/// - Affected domains that should address the issue
/// 
/// Used by BalanceAnalyzerAgent to report game balance problems.
/// </summary>
public sealed record BalanceIssue
{
    public required string IssueId { get; init; }
    public required BalanceCategory Category { get; init; }
    public required BalanceSeverity Severity { get; init; }
    public required string Title { get; init; }
    public required string Description { get; init; }

    /// <summary>
    /// Statistical evidence supporting this issue.
    /// </summary>
    public IReadOnlyList<StatisticalEvidence> Evidence { get; init; } = Array.Empty<StatisticalEvidence>();

    /// <summary>
    /// Suggested fixes generated by AI.
    /// </summary>
    public IReadOnlyList<SuggestedFix> SuggestedFixes { get; init; } = Array.Empty<SuggestedFix>();

    /// <summary>
    /// Which design agents should address this issue.
    /// </summary>
    public IReadOnlyList<string> AffectedDomains { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Statistical evidence for a balance issue.
/// </summary>
public sealed record StatisticalEvidence
{
    public required string Metric { get; init; }
    public required double ObservedValue { get; init; }
    public required double ExpectedValue { get; init; }
    public double? Deviation { get; init; }
    public int SampleSize { get; init; }
}

/// <summary>
/// A suggested fix for a balance issue.
/// </summary>
public sealed record SuggestedFix
{
    public required string Description { get; init; }
    public required double Confidence { get; init; }
    public IReadOnlyDictionary<string, object> Parameters { get; init; } =
        new Dictionary<string, object>();
}

/// <summary>
/// Categories of balance issues.
/// </summary>
public enum BalanceCategory
{
    Combat,
    Economy,
    Progression,
    Difficulty,
    Pacing,
    Performance
}

/// <summary>
/// Severity levels for balance issues.
/// </summary>
public enum BalanceSeverity
{
    Minor,      // Noticeable but not game-breaking
    Moderate,   // Impacts enjoyment
    Major,      // Significantly impacts gameplay
    Critical    // Game-breaking
}

/// <summary>
/// Playtest report with balance analysis.
/// </summary>
public sealed record PlaytestReport
{
    public required string ReportId { get; init; }
    public IReadOnlyList<string> SessionIds { get; init; } = Array.Empty<string>();
    public DateTimeOffset GeneratedAt { get; init; }
    public IReadOnlyList<BalanceIssue> Issues { get; init; } = Array.Empty<BalanceIssue>();
    public string? Summary { get; init; }
}

