namespace Nexo.Orchestration.Playtest.Models;

/// <summary>
/// A balance issue identified from playtest analysis.
/// 
/// Contains:
/// - Issue identification, category, and severity
/// - Title and description
/// - Statistical evidence supporting the issue
/// - Suggested fixes from AI analysis
/// - Affected domains that should address the issue
/// 
/// Used by BalanceAnalyzerAgent to report game balance problems.
/// </summary>
public sealed record BalanceIssue
{
    /// <summary>Unique issue identifier.</summary>
    public required string IssueId { get; init; }

    /// <summary>Balance category for the issue.</summary>
    public required BalanceCategory Category { get; init; }

    /// <summary>Severity rating assigned to the issue.</summary>
    public required BalanceSeverity Severity { get; init; }

    /// <summary>Short title for operator display.</summary>
    public required string Title { get; init; }

    /// <summary>Detailed description of the balance problem.</summary>
    public required string Description { get; init; }

    /// <summary>
    /// Statistical evidence supporting this issue.
    /// </summary>
    public IReadOnlyList<StatisticalEvidence> Evidence { get; init; } = Array.Empty<StatisticalEvidence>();

    /// <summary>
    /// Suggested fixes generated by AI.
    /// </summary>
    public IReadOnlyList<SuggestedFix> SuggestedFixes { get; init; } = Array.Empty<SuggestedFix>();

    /// <summary>
    /// Which design agents should address this issue.
    /// </summary>
    public IReadOnlyList<string> AffectedDomains { get; init; } = Array.Empty<string>();
}
