<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" Version="1.3.9" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Nexo.Core.Application/Nexo.Core.Application.csproj" />
    <ProjectReference Include="../../src/Nexo.Core.Domain/Nexo.Core.Domain.csproj" />
    <ProjectReference Include="../../src/Nexo.Shared/Nexo.Shared.csproj" />
    <ProjectReference Include="../../src/Nexo.Examples/Nexo.Examples.csproj" />
  </ItemGroup>
</Project>
